### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by pine** [emoji-gen/Emoji-Android#5]
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:325)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by javax.net.ssl.SSLPeerUnverifiedException: Hostname test.slack.com.slack.com not verified:
    certificate: sha256/Sg10y6GSAWjaCGBsTm2HWEztd/Hu55IA6r3nbfXC6BU=
    DN: CN=*.slack.com,O=Slack Technologies\, Inc.,L=San Francisco,ST=California,C=US
    subjectAltNames: [slack.com, *.slack.com]
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:276)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at okhttp3.RealCall.execute(RealCall.java:63)
       at moe.pine.emoji.lib.slack.HttpClient.doGetCustomizeEmoji(HttpClient.kt:42)
       at moe.pine.emoji.lib.slack.AuthClient.auth(AuthClient.kt:16)
       at moe.pine.emoji.task.AuthAndSaveTask.doInBackground(AuthAndSaveTask.kt:39)
       at moe.pine.emoji.task.AuthAndSaveTask.doInBackground(AuthAndSaveTask.kt:20)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by pine** [comment]
https://github.com/emoji-gen/Emoji-Android/commit/7f1d30030108b3fb61b7ae190f0d804e3879ff6b
